title: Sarika Sakore
logo: /assets/img/logo.png
description: Data Scientist aspirant would like to work in NLP and ML
Support Executive @ TCS, Pune
Visit: https://www.linkedin.com/in/sarika03/
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
