title: Sarika Sakore
logo: /assets/img/logo.png
description: Data Scientist aspirant and would like to work in NLP and ML <br><br> Support Executive @ TCS, Pune <br><br><br><br> 
Visit: https://www.linkedin.com/in/sarika03/

theme: jekyll-theme-minimal
