title: Sarika Sakore
logo: /assets/img/logo.png
description: Data Scientist aspirant and would like to work in NLP and ML <br><br> Support Executive @ TCS, Pune <br><br>
another_url: https://www.linkedin.com/in/sarika03/
show_downloads: true
google_analytics:

theme: jekyll-theme-minimal
