title: Sarika Sakore
logo: /assets/img/logo.png
description: Data Scientist aspirant would like to work in NLP and ML <br> Support Executive @ TCS, Pune 

Visit: https://www.linkedin.com/in/sarika03/

theme: jekyll-theme-minimal
